export { default as CompanyDetailsPage } from './company-details.page';
export { default as DigitalContractReviewPage } from './digital-contract-review.page';
export { default as DigitalContractSuccessPage } from './digital-contract-success.page';
export { default as HomePage } from './home.page';
export { default as LoginPage } from './login.page';
export { default as SelectServicesPage } from './select-service.page';
export { default as SignUpPage } from './sign-up.page';
export { default as UserDetailsPage } from './user-details.page';
export { default as UserVerificationPage } from './user-verification.page';
